version: '3.8'

services:
  backend:
    build: ./backend
    container_name: tru2u-backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://db:27017/tru2uDB
      - JWT_SECRET=${JWT_SECRET}
      - PI_API_KEY=${PI_API_KEY}
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: tru2u-frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://backend:5000

  db:
    image: mongo:4.4
    container_name: tru2u-db
    ports:
      - "27017:27017"
    volumes:
      - db-data:/data/db

volumes:
  db-data:
